apiVersion: v1
kind: Service
metadata:
  name: user-admin-app-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: user-admin-app
